---
plugin: hive_services
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    initialize_roles:
      - python-aptk
      - nginx-init
    volumes:
      - source: nginx_conf
        target: /etc/nginx/conf.d
        type: volume
        drbd:
          fstype: xfs
          size: 500M
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - source: mysql_data
        target: /var/lib/mysql
        type: volume
        drbd:
          fstype: xfs
          size: 3G
    backup_scripts:
      - name: redmine_db
        backup_command: mysqldump -u root -pexample redmine > /root/today.sql
        restore_command: mysql -u root -pexample redmine < /root/today.sql
        backup_file: /root/today.sql
        restore_file: /root/today.sql
        ext: sql
        cleanup_days_before: 3
  redmine:
    image: redmine
    restart_config:
      condition: "on-failure"
      delay: 5s
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - source: redmine_files
        target: /usr/src/redmine/files
        type: volume
        drbd:
          fstype: xfs
          size: 1G
